services:
  shop-service:
    build:
      context: ./shop-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db_shop
      - rabbitmq
    environment:
      SECRET_KEY: kektest
      DB_DIALECT: postgres
      DB_HOST: db_shop
      DB_PORT: 5432
      DB_USERNAME: shop_user
      DB_PASSWORD: shop_password
      DB_NAME: shop_db

  user-auth-service:
    build:
      context: user-auth-service
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db_user
      - rabbitmq
    environment:
      SECRET_KEY: kektest
      DB_HOST: db_user
      DB_DIALECT: postgres
      DB_PORT: 5432
      DB_USERNAME: user_user
      DB_PASSWORD: user_password
      DB_NAME: user_db

  gateway:
    build:
      context: ./deployment/gateway/src
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - shop-service
      - user-auth-service

  db_shop:
    image: postgres:13
    environment:
      POSTGRES_USER: shop_user
      POSTGRES_PASSWORD: shop_password
      POSTGRES_DB: shop_db
    ports:
      - "5432:5432"

  db_user:
    image: postgres:13
    environment:
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: user_password
      POSTGRES_DB: user_db
    ports:
      - "5433:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  default:
    name: my_network
